# Generated by Django 5.2.5 on 2025-09-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
    ]
