# Generated by Django 5.2.5 on 2025-08-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_ativo_profissional_ativo_servico_ativo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente_cliente',
        ),
        migrations.AlterModelTable(
            name='profissional',
            table='cliente_profissional',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='cliente_servico',
        ),
    ]
