# Generated by Django 5.2.5 on 2025-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_remove_agendamento_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
