# Generated by Django 5.2.5 on 2025-08-25 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação')),
                ('status', models.CharField(default='Agendado', max_length=20, verbose_name='Estado do agendamento')),
                ('data_agendada', models.DateTimeField(verbose_name='Dia agendado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.profissional', verbose_name='Profissionais')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.servico', verbose_name='Serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
