# Generated by Django 5.2.5 on 2025-09-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
