# Generated by Django 5.2.5 on 2025-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_profissional_especialidade_profissional_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='data_contratacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Contratação'),
        ),
    ]
